groups:
  - name: pipeline_alerts
    rules:
      - alert: HighNullValueRate
        expr: (sum(null_value_count) / sum(total_records)) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High rate of null values detected"
          description: "More than 5% of records contain null values for the past 5 minutes."

      - alert: HighDuplicateRate
        expr: (sum(duplicate_record_count) / sum(total_records)) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate of duplicate records detected"
          description: "More than 1% of records are duplicates for the past 5 minutes."

      - alert: PipelineProcessingTime
        expr: avg(processing_time_seconds) > 60
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High pipeline processing time"
          description: "The average processing time for the pipeline exceeds 60 seconds."

      - alert: HighLoanDefaultRate
        expr: (sum(defaulted_loans) / sum(total_loans)) > 0.1
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High loan default rate detected"
          description: "More than 10% of loans have defaulted in the past 10 minutes."

      - alert: DatabaseConnectionErrors
        expr: increase(db_connection_errors_total[5m]) > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Database connection errors detected"
          description: "More than 10 database connection errors in the past 5 minutes."
